[1;32mINFO[0m - 2016-12-25 12:37:30,928 - session started
[1;32mINFO[0m - 2016-12-25 12:37:31,145 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:37:31,149 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:37:31,150 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 12:37:31,266 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 12:37:31,267 - Logging in...
[1;32mINFO[0m - 2016-12-25 12:37:31,269 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 12:37:31,387 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 12:37:31,549 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 12:41:28,758 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 12:41:28,759 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 12:41:28,760 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 12:41:38,186 - session started
[1;32mINFO[0m - 2016-12-25 12:41:38,401 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:41:38,403 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:43:42,702 - session started
[1;32mINFO[0m - 2016-12-25 12:43:42,928 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:43:42,930 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:47:46,379 - session started
[1;32mINFO[0m - 2016-12-25 12:47:46,604 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:47:46,606 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:49:06,788 - session started
[1;32mINFO[0m - 2016-12-25 12:49:07,014 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:49:07,017 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:50:01,224 - session started
[1;32mINFO[0m - 2016-12-25 12:50:01,440 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:50:01,442 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:51:58,518 - session started
[1;32mINFO[0m - 2016-12-25 12:51:58,732 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:51:58,735 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:53:56,202 - session started
[1;32mINFO[0m - 2016-12-25 12:53:56,418 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:53:56,420 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:54:35,459 - session started
[1;32mINFO[0m - 2016-12-25 12:54:35,680 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:54:35,683 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:54:35,684 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 12:54:35,796 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 12:54:35,797 - Logging in...
[1;32mINFO[0m - 2016-12-25 12:54:35,798 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 12:54:35,922 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 12:54:36,073 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 12:55:01,566 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 12:55:01,567 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 12:55:01,568 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 12:55:41,144 - session started
[1;32mINFO[0m - 2016-12-25 12:55:41,376 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:55:41,378 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:56:50,326 - session started
[1;32mINFO[0m - 2016-12-25 12:56:50,544 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:56:50,547 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:58:02,677 - session started
[1;32mINFO[0m - 2016-12-25 12:58:02,898 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:58:02,901 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 12:58:32,698 - session started
[1;32mINFO[0m - 2016-12-25 12:58:32,917 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 12:58:32,920 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:01:25,001 - session started
[1;32mINFO[0m - 2016-12-25 13:01:25,218 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:01:25,220 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:01:28,038 - session started
[1;32mINFO[0m - 2016-12-25 13:01:28,257 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:01:28,260 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:01:33,682 - session started
[1;32mINFO[0m - 2016-12-25 13:01:33,897 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:01:33,899 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:01:37,362 - session started
[1;32mINFO[0m - 2016-12-25 13:01:37,578 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:01:37,580 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:01:47,075 - session started
[1;32mINFO[0m - 2016-12-25 13:01:47,290 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:01:47,293 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:06:14,397 - session started
[1;32mINFO[0m - 2016-12-25 13:06:14,613 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:06:14,615 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:06:46,593 - session started
[1;32mINFO[0m - 2016-12-25 13:06:46,808 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:06:46,811 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:07:02,756 - session started
[1;32mINFO[0m - 2016-12-25 13:07:02,978 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:07:02,980 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:07:08,373 - session started
[1;32mINFO[0m - 2016-12-25 13:07:08,588 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:07:08,590 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:09:00,751 - session started
[1;32mINFO[0m - 2016-12-25 13:09:00,967 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:09:00,970 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:09:09,131 - session started
[1;32mINFO[0m - 2016-12-25 13:09:09,353 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:09:09,355 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:09:31,118 - session started
[1;32mINFO[0m - 2016-12-25 13:09:31,334 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:09:31,336 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:10:41,444 - session started
[1;32mINFO[0m - 2016-12-25 13:10:41,660 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:10:41,662 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:11:57,872 - session started
[1;32mINFO[0m - 2016-12-25 13:11:58,098 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:11:58,101 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:19:13,451 - session started
[1;32mINFO[0m - 2016-12-25 13:19:13,697 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:19:13,700 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:19:25,526 - session started
[1;32mINFO[0m - 2016-12-25 13:19:25,756 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:19:25,758 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:20:34,026 - session started
[1;32mINFO[0m - 2016-12-25 13:20:34,241 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:20:34,244 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:21:28,194 - session started
[1;32mINFO[0m - 2016-12-25 13:21:28,413 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:21:28,416 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:22:38,904 - session started
[1;32mINFO[0m - 2016-12-25 13:22:39,122 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:22:39,125 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:23:02,503 - session started
[1;32mINFO[0m - 2016-12-25 13:23:02,732 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:23:02,735 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:24:21,788 - session started
[1;32mINFO[0m - 2016-12-25 13:24:22,006 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:24:22,008 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:24:30,245 - session started
[1;32mINFO[0m - 2016-12-25 13:24:30,460 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:24:30,462 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:25:32,581 - session started
[1;32mINFO[0m - 2016-12-25 13:25:32,801 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:25:32,804 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:25:58,575 - session started
[1;32mINFO[0m - 2016-12-25 13:25:58,789 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:25:58,792 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:28:51,220 - session started
[1;32mINFO[0m - 2016-12-25 13:28:51,435 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:28:51,437 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:29:40,212 - session started
[1;32mINFO[0m - 2016-12-25 13:29:40,436 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:29:40,439 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:30:08,309 - session started
[1;32mINFO[0m - 2016-12-25 13:30:08,544 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:30:08,547 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:33:38,258 - session started
[1;32mINFO[0m - 2016-12-25 13:33:38,476 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:33:38,479 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:35:25,249 - session started
[1;32mINFO[0m - 2016-12-25 13:35:25,485 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:35:25,488 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:35:34,053 - session started
[1;32mINFO[0m - 2016-12-25 13:35:34,270 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:35:34,272 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:35:58,024 - session started
[1;32mINFO[0m - 2016-12-25 13:35:58,256 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:35:58,258 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:41:41,426 - session started
[1;32mINFO[0m - 2016-12-25 13:41:41,645 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:41:41,647 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:41:56,407 - session started
[1;32mINFO[0m - 2016-12-25 13:41:56,623 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:41:56,625 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:44:06,727 - session started
[1;32mINFO[0m - 2016-12-25 13:44:06,963 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:44:06,965 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:45:06,788 - session started
[1;32mINFO[0m - 2016-12-25 13:45:07,032 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:45:07,034 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:45:23,463 - session started
[1;32mINFO[0m - 2016-12-25 13:45:23,678 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:45:23,680 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:49:28,745 - session started
[1;32mINFO[0m - 2016-12-25 13:49:28,971 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:49:28,974 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:50:15,971 - session started
[1;32mINFO[0m - 2016-12-25 13:50:16,186 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:50:16,189 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:50:16,190 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 13:50:16,324 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 13:50:16,325 - Logging in...
[1;32mINFO[0m - 2016-12-25 13:50:16,326 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 13:50:16,460 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 13:50:16,462 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 13:50:37,334 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 13:50:37,336 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 13:50:37,336 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 13:54:43,280 - session started
[1;32mINFO[0m - 2016-12-25 13:54:43,498 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:54:43,500 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:54:43,501 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 13:54:43,614 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 13:54:43,614 - Logging in...
[1;32mINFO[0m - 2016-12-25 13:54:43,615 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 13:54:43,714 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 13:54:43,715 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 13:54:46,550 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 13:54:46,552 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 13:54:46,553 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 13:59:31,185 - session started
[1;32mINFO[0m - 2016-12-25 13:59:31,413 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 13:59:31,415 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 13:59:31,416 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 13:59:31,539 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 13:59:31,539 - Logging in...
[1;32mINFO[0m - 2016-12-25 13:59:31,540 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 13:59:31,665 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 13:59:31,666 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 13:59:36,310 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 13:59:36,312 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 13:59:36,312 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:02:40,736 - session started
[1;32mINFO[0m - 2016-12-25 14:02:40,951 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:02:40,953 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:02:40,954 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:02:41,433 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:02:41,433 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:02:41,434 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:02:41,551 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:02:41,553 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:02:45,350 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:02:45,352 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:02:45,353 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:03:11,119 - session started
[1;32mINFO[0m - 2016-12-25 14:03:11,346 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:03:11,348 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:03:11,349 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:03:11,485 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:03:11,486 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:03:11,486 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:03:11,622 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:03:11,624 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:03:12,894 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:03:12,896 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:03:12,897 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:04:46,199 - session started
[1;32mINFO[0m - 2016-12-25 14:04:46,415 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:04:46,417 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:04:46,418 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:04:46,540 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:04:46,541 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:04:46,541 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:04:46,658 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:04:46,660 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:04:47,270 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:04:47,272 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:04:47,273 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:05:18,942 - session started
[1;32mINFO[0m - 2016-12-25 14:05:19,162 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:05:19,164 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:05:19,165 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:05:19,278 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:05:19,278 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:05:19,279 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:05:19,429 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:05:19,431 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:05:20,286 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:05:20,288 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:05:20,288 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:07:23,887 - session started
[1;32mINFO[0m - 2016-12-25 14:07:24,106 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:07:24,109 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:07:24,109 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:07:24,225 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:07:24,226 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:07:24,226 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:07:24,348 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:07:24,350 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:07:25,990 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:07:25,991 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:07:25,991 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:09:02,071 - session started
[1;32mINFO[0m - 2016-12-25 14:09:02,309 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:09:02,311 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:09:02,328 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:09:02,459 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:09:02,459 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:09:02,460 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:09:02,587 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:09:02,587 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:09:17,077 - session started
[1;32mINFO[0m - 2016-12-25 14:09:17,295 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:09:17,297 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:09:17,298 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:09:17,413 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:09:17,414 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:09:17,414 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:09:42,745 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:09:42,746 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:09:42,747 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:09:42,864 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:09:42,864 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:10:07,382 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:10:07,384 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:10:07,384 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:10:23,017 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:10:23,018 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:10:23,019 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:10:23,126 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:10:23,127 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:10:33,392 - session started
[1;32mINFO[0m - 2016-12-25 14:10:33,612 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:10:33,615 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:10:33,616 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:10:33,729 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:10:33,730 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:10:33,731 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:10:53,630 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:10:53,632 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:10:53,633 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:11:03,270 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:11:03,271 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:11:03,272 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:11:03,376 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:11:03,376 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:11:43,537 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:11:43,537 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:11:43,538 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:11:43,651 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:11:43,652 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:12:23,794 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:12:23,794 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:12:23,795 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:12:23,902 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:12:23,903 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:12:34,508 - session started
[1;32mINFO[0m - 2016-12-25 14:12:34,722 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:12:34,725 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:12:34,726 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:12:34,848 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:12:34,848 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:12:34,849 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:12:58,598 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:12:58,600 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:12:58,601 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:13:04,053 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:13:04,054 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:13:04,054 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:13:04,179 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:13:04,179 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:13:44,314 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:13:44,315 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:13:44,316 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:13:44,424 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:13:44,425 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:14:24,594 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:14:24,595 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:14:24,595 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:14:24,711 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:14:24,712 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:15:04,892 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:15:04,893 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:15:04,894 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:15:05,026 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:15:05,026 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:15:45,188 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:15:45,188 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:15:45,189 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:15:45,316 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:15:45,317 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:16:25,516 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:16:25,517 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:16:25,518 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:16:25,630 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:16:25,631 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:17:05,801 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:17:05,802 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:17:05,803 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:17:06,013 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:17:06,013 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:17:46,175 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:17:46,175 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:17:46,176 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:17:46,329 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:17:46,330 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:18:26,498 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:18:26,499 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:18:26,500 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:18:26,613 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:18:26,613 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:19:06,777 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:19:06,777 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:19:06,778 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:19:06,881 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:19:06,882 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:19:47,014 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:19:47,015 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:19:47,016 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:19:47,122 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:19:47,123 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:19:57,361 - session started
[1;32mINFO[0m - 2016-12-25 14:19:57,578 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:19:57,580 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:19:57,581 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:19:57,696 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:19:57,697 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:19:57,698 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:19:59,886 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:19:59,888 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:19:59,888 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:20:02,467 - session started
[1;32mINFO[0m - 2016-12-25 14:20:02,685 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:20:02,687 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:20:02,688 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:20:02,800 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:20:02,800 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:20:02,801 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:20:27,301 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:20:27,301 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:20:27,302 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:20:27,423 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:20:27,424 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:20:30,423 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:20:30,424 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:20:30,425 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:20:36,485 - session started
[1;32mINFO[0m - 2016-12-25 14:20:36,699 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:20:36,701 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:20:36,702 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:20:36,824 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:20:36,826 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:20:36,827 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:21:01,438 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:21:01,440 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:21:01,441 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:21:07,556 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:21:07,556 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:21:07,557 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:21:07,667 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:21:07,668 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:21:47,824 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:21:47,824 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:21:47,825 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:21:47,963 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:21:47,963 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:22:17,564 - session started
[1;32mINFO[0m - 2016-12-25 14:22:17,781 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:22:17,784 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:22:17,802 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:22:17,924 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:22:17,925 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:22:17,925 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:22:28,139 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:22:28,140 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:22:28,141 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:22:28,264 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:22:28,264 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:22:34,433 - session started
[1;32mINFO[0m - 2016-12-25 14:22:34,647 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:22:34,650 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:22:34,651 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:22:34,766 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:22:34,766 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:22:34,767 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:23:08,414 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:23:08,415 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:23:08,416 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:23:08,542 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:23:08,543 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:23:48,718 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:23:48,718 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:23:48,719 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:23:48,832 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:23:48,832 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:24:27,518 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:24:27,520 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:24:27,521 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:24:28,960 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:24:28,961 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:24:28,962 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:24:29,082 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:24:29,082 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    else:
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    if command == "ACCEPTED":
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:24:29,157 - session started
[1;32mINFO[0m - 2016-12-25 14:24:29,370 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:24:29,373 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:24:29,374 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:24:29,488 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:24:29,488 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:24:29,489 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:24:32,582 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:24:32,584 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:24:32,585 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:25:01,441 - session started
[1;32mINFO[0m - 2016-12-25 14:25:01,656 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:25:01,659 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:25:01,659 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:25:01,782 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:25:01,783 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:25:01,784 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:25:09,238 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:25:09,238 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:25:09,239 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:25:09,360 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:25:09,361 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    else:
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    if command == "ACCEPTED":
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:25:18,015 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:25:18,016 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:25:18,017 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:25:49,625 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:25:49,625 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:25:49,626 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:25:49,931 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:25:49,932 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:26:19,183 - session started
[1;32mINFO[0m - 2016-12-25 14:26:19,399 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:26:19,402 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:26:19,403 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:26:19,524 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:26:19,524 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:26:19,525 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:26:26,047 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:26:26,048 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:26:26,049 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:26:30,088 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:26:30,089 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:26:30,090 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:26:30,203 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:26:30,203 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:27:03,888 - session started
[1;32mINFO[0m - 2016-12-25 14:27:04,106 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:27:04,108 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:27:04,109 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:27:04,224 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:27:04,225 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:27:04,226 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:27:10,336 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:27:10,337 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:27:10,338 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:27:10,490 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:27:10,490 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:27:50,676 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:27:50,677 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:27:50,677 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:27:50,817 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:27:50,817 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:28:30,994 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:28:30,995 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:28:30,996 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:28:31,134 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:28:31,134 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:29:11,264 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:29:11,265 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:29:11,266 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:29:11,381 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:29:11,381 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:29:51,537 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:29:51,538 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:29:51,539 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:29:51,639 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:29:51,640 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:29:54,150 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:29:54,152 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:29:54,153 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:29:55,721 - session started
[1;32mINFO[0m - 2016-12-25 14:29:55,936 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:29:55,938 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:29:55,939 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:29:56,061 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:29:56,062 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:29:56,063 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:29:57,607 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:29:57,608 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:29:57,609 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:30:31,783 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:30:31,783 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:30:31,784 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:30:31,893 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:30:31,894 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:30:55,467 - session started
[1;32mINFO[0m - 2016-12-25 14:30:55,681 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:30:55,684 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:30:55,685 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:30:55,807 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:30:55,807 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:30:55,808 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:31:12,034 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:31:12,035 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:31:12,036 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:31:12,135 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:31:12,136 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:31:52,629 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:31:52,629 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:31:52,630 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:31:52,751 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:31:52,752 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:32:32,903 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:32:32,904 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:32:32,905 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:32:33,019 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:32:33,020 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:32:50,783 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:32:50,784 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:32:50,785 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:33:06,769 - session started
[1;32mINFO[0m - 2016-12-25 14:33:06,993 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:33:06,995 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:33:06,996 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:33:07,110 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:33:07,110 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:33:07,111 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:33:13,213 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:33:13,214 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:33:13,215 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:33:13,435 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:33:13,436 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:33:24,606 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:33:24,608 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:33:24,609 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:33:46,663 - session started
[1;32mINFO[0m - 2016-12-25 14:33:46,878 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:33:46,880 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:33:46,881 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:33:46,994 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:33:46,995 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:33:46,996 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:33:53,595 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:33:53,596 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:33:53,597 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:33:53,721 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:33:53,722 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    else:
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.channels = ChannelList()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    if command == "ACCEPTED":
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:34:26,255 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:34:26,256 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:34:26,257 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:34:27,437 - session started
[1;32mINFO[0m - 2016-12-25 14:34:27,651 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:34:27,653 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:34:27,654 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:34:27,767 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:34:27,767 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:34:27,768 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:34:32,310 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:34:32,312 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:34:32,313 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:34:33,876 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:34:33,877 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:34:33,878 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:34:33,988 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:34:33,989 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    for cmd in commands:
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.register(self.uname, self.password)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.uname = username
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    for cmd in commands:
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    if command == "MOTD":
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:34:51,953 - session started
[1;32mINFO[0m - 2016-12-25 14:34:52,171 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:34:52,173 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:34:52,174 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:34:52,290 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:34:52,291 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:34:52,291 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:34:53,750 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:34:53,752 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:34:53,753 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:35:14,185 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:35:14,185 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:35:14,186 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:35:14,306 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:35:14,307 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    else:
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    if command == "ACCEPTED":
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:35:26,209 - session started
[1;32mINFO[0m - 2016-12-25 14:35:26,425 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:35:26,427 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:35:26,428 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:35:26,551 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:35:26,551 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:35:26,552 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:35:28,183 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:35:28,184 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:35:28,185 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:35:54,491 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:35:54,492 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:35:54,492 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:35:54,614 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:35:54,614 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:36:32,257 - session started
[1;32mINFO[0m - 2016-12-25 14:36:32,472 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:36:32,474 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:36:32,475 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:36:32,597 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:36:32,597 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:36:32,598 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:36:34,757 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:36:34,758 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:36:34,759 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:36:34,864 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:36:34,865 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:37:15,013 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:37:15,013 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:37:15,014 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:37:15,121 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:37:15,122 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:37:55,265 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:37:55,266 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:37:55,267 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:37:55,387 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:37:55,388 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;31mERROR[0m - 2016-12-25 14:38:29,071 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:38:29,072 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:38:29,073 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:38:30,143 - session started
[1;32mINFO[0m - 2016-12-25 14:38:30,364 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:38:30,366 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:38:30,367 - Connecting to lobby.springrts.com:8200
[1;31mERROR[0m - 2016-12-25 14:38:30,482 - Can't convert 'bytes' object to str implicitly
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 288, in receive
    buf += nbuf
TypeError: Can't convert 'bytes' object to str implicitly
[1;31mERROR[0m - 2016-12-25 14:38:30,597 - Can't convert 'bytes' object to str implicitly
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 288, in receive
    buf += nbuf
TypeError: Can't convert 'bytes' object to str implicitly
[1;31mERROR[0m - 2016-12-25 14:38:30,721 - Can't convert 'bytes' object to str implicitly
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 288, in receive
    buf += nbuf
TypeError: Can't convert 'bytes' object to str implicitly
[1;31mERROR[0m - 2016-12-25 14:38:30,845 - Can't convert 'bytes' object to str implicitly
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 288, in receive
    buf += nbuf
TypeError: Can't convert 'bytes' object to str implicitly
[1;31mERROR[0m - 2016-12-25 14:38:30,969 - Can't convert 'bytes' object to str implicitly
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 288, in receive
    buf += nbuf
TypeError: Can't convert 'bytes' object to str implicitly
[1;31mERROR[0m - 2016-12-25 14:38:31,807 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:38:31,808 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:38:31,809 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:38:50,852 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:38:50,853 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:38:50,853 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:38:50,979 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:38:50,979 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:38:55,842 - session started
[1;32mINFO[0m - 2016-12-25 14:38:56,068 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:38:56,070 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:38:56,072 - Connecting to lobby.springrts.com:8200
[1;31mERROR[0m - 2016-12-25 14:39:10,174 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:39:10,176 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:39:10,177 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:39:31,140 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:39:31,141 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:39:31,142 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:39:31,263 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:39:31,263 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:39:40,811 - session started
[1;32mINFO[0m - 2016-12-25 14:39:41,031 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:39:41,034 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:39:41,035 - Connecting to lobby.springrts.com:8200
[1;31mERROR[0m - 2016-12-25 14:39:45,055 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:39:45,056 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:39:45,057 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:40:11,436 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:40:11,436 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:40:11,437 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:40:11,563 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:40:11,563 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    self.parsecommand(c, args)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:40:21,642 - session started
[1;32mINFO[0m - 2016-12-25 14:40:21,857 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:40:21,860 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:40:21,860 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:40:21,976 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:40:21,977 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:40:21,977 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:40:27,286 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:40:27,288 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:40:27,289 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:40:51,718 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:40:51,719 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:40:51,720 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:40:51,832 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:40:51,833 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:41:04,167 - session started
[1;32mINFO[0m - 2016-12-25 14:41:04,382 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:41:04,384 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:41:04,385 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:41:04,499 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:41:04,499 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:41:04,500 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:41:06,510 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:41:06,512 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:41:06,513 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:41:31,998 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:41:31,999 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:41:31,999 - Trying to login with username TurBot 
[1;31mERROR[0m - 2016-12-25 14:41:32,121 - Cannot connect, retrying in 40 secs...
[1;31mERROR[0m - 2016-12-25 14:41:32,122 - 'MainApp' object has no attribute 'threads'
Traceback (most recent call last):
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 69, in connect
    res = self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 183, in parsecommand
    self.events.onconnected()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 76, in do_login
    "Newbot", 2400, self.config.get(self.section, "lanip", "*"))
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 103, in login
    self.receive()
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 297, in receive
    args = cmd.split(" ")[1:]
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/client.py", line 204, in parsecommand
    self.events.onloggedin(self.socket)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/main.py", line 34, in onlogin
    self.start_thread(self.tasclient.mainloop)
  File "/home/turboss/Sources/spring_bot/wikibot/lib/python3.5/site-packages/tasbot/plugin.py", line 93, in start_thread
    self.threads.append(PluginThread(func, *args))
AttributeError: 'MainApp' object has no attribute 'threads'
[1;32mINFO[0m - 2016-12-25 14:41:38,025 - MainApp got SystemExit
[1;32mINFO[0m - 2016-12-25 14:41:38,026 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:41:38,027 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:41:40,392 - MainApp got SystemExit
[1;32mINFO[0m - 2016-12-25 14:41:40,394 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:41:40,394 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:41:43,648 - session started
[1;32mINFO[0m - 2016-12-25 14:41:43,862 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:41:43,865 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:41:43,866 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:41:43,977 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:41:43,978 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:41:43,979 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:41:44,313 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 14:41:44,437 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 14:41:49,806 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:41:49,808 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:41:49,809 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 14:44:01,984 - session started
[1;32mINFO[0m - 2016-12-25 14:44:02,201 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:44:02,204 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:44:02,205 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:44:02,327 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:44:02,327 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:44:02,328 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:44:02,471 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 14:44:02,614 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 14:44:04,543 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:44:04,544 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:44:04,545 - join_channels Unloaded
[1;31mERROR[0m - 2016-12-25 14:44:12,480 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 14:44:37,515 - session started
[1;32mINFO[0m - 2016-12-25 14:44:37,729 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:44:37,732 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:44:37,733 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:44:37,854 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:44:37,856 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:44:37,857 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:44:37,972 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 14:44:38,138 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 14:45:10,151 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 14:45:10,152 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:45:10,153 - join_channels Unloaded
[1;31mERROR[0m - 2016-12-25 14:45:17,644 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 14:45:29,203 - session started
[1;32mINFO[0m - 2016-12-25 14:45:29,419 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:45:29,422 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:45:29,435 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:45:29,569 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:45:29,570 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:45:29,570 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:45:29,704 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 14:45:29,791 - [GOOD] Joined #jauriarts
[1;32mINFO[0m - 2016-12-25 14:46:23,817 - MainApp got SystemExit
[1;32mINFO[0m - 2016-12-25 14:46:23,818 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 14:46:23,819 - join_channels Unloaded
[1;31mERROR[0m - 2016-12-25 14:46:29,767 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 14:47:46,207 - session started
[1;32mINFO[0m - 2016-12-25 14:47:46,422 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 14:47:46,424 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 14:47:46,425 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 14:47:46,542 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 14:47:46,542 - Logging in...
[1;32mINFO[0m - 2016-12-25 14:47:46,543 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 14:47:46,655 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 14:47:46,812 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 15:07:41,318 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 15:07:41,319 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 15:07:41,321 - wiki Unloaded
[1;31mERROR[0m - 2016-12-25 15:07:47,649 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 15:08:46,112 - session started
[1;32mINFO[0m - 2016-12-25 15:08:46,355 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 15:08:46,357 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 15:08:46,358 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 15:08:46,481 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 15:08:46,481 - Logging in...
[1;32mINFO[0m - 2016-12-25 15:08:46,482 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 15:08:47,246 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 15:08:47,340 - [GOOD] Joined #moddev
[1;32mINFO[0m - 2016-12-25 15:08:47,411 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 15:09:17,423 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 15:09:17,423 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 15:09:17,424 - wiki Unloaded
[1;31mERROR[0m - 2016-12-25 15:09:22,623 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 15:11:51,058 - session started
[1;32mINFO[0m - 2016-12-25 15:11:51,316 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 15:11:51,319 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 15:11:51,320 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 15:11:51,434 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 15:11:51,435 - Logging in...
[1;32mINFO[0m - 2016-12-25 15:11:51,435 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 15:11:51,628 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 15:11:51,748 - [GOOD] Joined #moddev
[1;32mINFO[0m - 2016-12-25 15:11:51,787 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 15:13:21,215 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 15:13:21,216 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 15:13:21,216 - wiki Unloaded
[1;31mERROR[0m - 2016-12-25 15:13:26,216 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 15:16:30,050 - session started
[1;32mINFO[0m - 2016-12-25 15:16:30,294 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 15:16:30,296 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 15:16:30,297 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 15:16:30,412 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 15:16:30,412 - Logging in...
[1;32mINFO[0m - 2016-12-25 15:16:30,413 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 15:16:30,533 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 15:16:30,691 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 15:16:52,375 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 15:16:52,376 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 15:16:52,377 - wiki Unloaded
[1;31mERROR[0m - 2016-12-25 15:17:00,557 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 15:25:29,795 - session started
[1;32mINFO[0m - 2016-12-25 15:25:30,045 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 15:25:30,050 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 15:25:30,051 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 15:25:30,188 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 15:25:30,188 - Logging in...
[1;32mINFO[0m - 2016-12-25 15:25:30,189 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 15:25:30,329 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 15:25:30,508 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 16:03:54,935 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 16:03:54,937 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 16:03:54,938 - join_channels Unloaded
[1;31mERROR[0m - 2016-12-25 16:04:02,148 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 16:04:31,788 - session started
[1;32mINFO[0m - 2016-12-25 16:04:32,090 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 16:04:32,093 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 16:04:32,095 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 16:04:33,084 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 16:04:33,085 - Logging in...
[1;32mINFO[0m - 2016-12-25 16:04:33,086 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 16:04:33,219 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 16:04:33,338 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 16:04:34,895 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 16:04:34,897 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 16:04:34,897 - wiki Unloaded
[1;31mERROR[0m - 2016-12-25 16:04:42,444 - 1 threads left alive after destroy was called
[1;32mINFO[0m - 2016-12-25 16:04:56,990 - session started
[1;32mINFO[0m - 2016-12-25 16:04:57,228 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 16:04:57,230 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 16:04:57,231 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 16:04:57,354 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 16:04:57,354 - Logging in...
[1;32mINFO[0m - 2016-12-25 16:04:57,355 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 16:04:57,497 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 16:04:57,665 - [GOOD] Joined #moddev
[1;32mINFO[0m - 2016-12-25 16:04:57,665 - [GOOD] Joined #jauriarts
[1;31mERROR[0m - 2016-12-25 22:27:46,777 - SIGINT, Exiting
[1;32mINFO[0m - 2016-12-25 22:27:46,807 - wiki Unloaded
[1;32mINFO[0m - 2016-12-25 22:27:46,808 - join_channels Unloaded
[1;32mINFO[0m - 2016-12-25 22:28:11,491 - session started
[1;32mINFO[0m - 2016-12-25 22:28:13,104 - [LOADED] Plugin wiki
[1;32mINFO[0m - 2016-12-25 22:28:13,121 - [LOADED] Plugin join_channels
[1;32mINFO[0m - 2016-12-25 22:28:13,123 - Connecting to lobby.springrts.com:8200
[1;32mINFO[0m - 2016-12-25 22:28:13,377 - [GOOD] Connected to server
[1;32mINFO[0m - 2016-12-25 22:28:13,377 - Logging in...
[1;32mINFO[0m - 2016-12-25 22:28:13,378 - Trying to login with username TurBot 
[1;32mINFO[0m - 2016-12-25 22:28:13,519 - [GOOD] Logged in
[1;32mINFO[0m - 2016-12-25 22:28:13,694 - [GOOD] Joined #moddev
[1;32mINFO[0m - 2016-12-25 22:28:13,695 - [GOOD] Joined #jauriarts
